# Generated by Django 5.2.15 on 2026-06-10 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_alter_school_name_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_no', models.CharField(max_length=50)),
                ('upi_number', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='learners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='schools.school')),
            ],
            options={
                'ordering': ['grade', 'first_name', 'last_name'],
                'unique_together': {('school', 'assessment_no')},
            },
        ),
    ]
